[main]
    separator = "-"
    description = "Freiwillige Feuerwehr Hamburg-Eppendorf - Technischer Zug"
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = true
    endorse = false
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "dartsass"

[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]
    [modules.fontawesome]
        inline = true
        debug = true
        skipMissing = false

[debugging]
    showJS = false
    showSCSS = false

[home]
    #sections = ["aktuelles", "einsaetze", "aufgaben"]
    sections = ["einsaetze"]
    fullCover = true
    centerHeadline = true
    style = "gradient-featured"
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 6
        align = "start"

[navigation]
    anchor = true
    logo = "/img/logo.png"
    color = "body"
    fixed = true
    offset = "3.8em"
    search = true
    breadcrumb = true
    toc = false
    sidebar = false
    size = "md"

[messages]
    placement = "bottom-right"

[sharing]
    enabled = false
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[favicon]
    logo = "/img/logo.png"
    sizes = [16, 32, 48]

[style]
    primary = "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    purge = false

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 
