# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - release

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

env:
  DART_VERSION: "1.66.1"

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install dart-sass
        working-directory: /opt
        run: >
          curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_VERSION}/dart-sass-${DART_VERSION}-linux-x64.tar.gz &&
          tar -xf dart-sass-${DART_VERSION}-linux-x64.tar.gz &&
          rm dart-sass-${DART_VERSION}-linux-x64.tar.gz &&
          echo "/opt/dart-sass/" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Node.js dependencies
        run: "npm install  --legacy-peer-deps"

      - name: Fetch resources directory from cache
        uses: actions/cache@v3
        with:
          path: resources
          key: ${{ runner.os }}-hugo-resources-directory-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-hugo-resources-directory

      - name: Build site
        run: >
          ls -la /opt/dart-sass &&
          whoami &&
          node_modules/.bin/hugo env &&
          npm run build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
